env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars:
    - warn
    - caughtErrors: none
  react/jsx-uses-react: 1  # Prevent 'never used' warning on react import
  react/jsx-uses-vars: 1  # Prevent 'never used' warning on component import
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
